name = "doichev-kostia"
main = "./packages/www/dist/_worker.js/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./packages/www/dist", binding = "ASSETS" }

routes = [{ pattern = "doichevkostia.dev", custom_domain = true }]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[vars]
SST_RESOURCE_Auth = '{"type":"sst.cloudflare.Worker","url":"https://doichev-kostia-dev-authscript.doichev-kostia.workers.dev"}'
