/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "GoogleOauthClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOauthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Auth": cloudflare.Service
    "AuthKv": cloudflare.KVNamespace
    "Dump": cloudflare.R2Bucket
  }
}
