/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "AuthService": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "GoogleOauthClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOauthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KnowledgeBaseWebhookSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AuthKv": cloudflare.KVNamespace
    "AuthWorker": cloudflare.Service
    "Bucket": cloudflare.R2Bucket
  }
}
