/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Auth": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "AuthKv": {
      "type": "sst.cloudflare.Kv"
    }
    "Dump": {
      "type": "sst.cloudflare.Bucket"
    }
    "GoogleOauthClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOauthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
