/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AuthKv": {
      "type": "sst.cloudflare.Kv"
    }
    "AuthService": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "AuthWorker": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Bucket": {
      "type": "sst.cloudflare.Bucket"
    }
    "GoogleOauthClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleOauthClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KnowledgeBaseWebhookSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
  }
}
